export const data = [
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
  {
    name: 'Amiah Pruitt',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 1,
  },
  {
    name: 'Ariana Lang',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 2,
  },
  {
    name: 'Aspen Schmit',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 3,
  },
  {
    name: 'Brycen Jimenez',
    company: 'Wucket Inc',
    Role: 'ux Designer',
    verified: true,
    status: 'active',
    id: 4,
  },
]
